config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks" }

  get "privacy_policies" => "privacy_policies#index", as: :privacy_policies
  get "terms_of_services" => "terms_of_services#index", as: :terms_of_services

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resource :contacts, only: [ :new, :create ]
  resources :quizzes
  resources :quiz_posts do
    collection do
      get :bookmarks
      post :create
      get "search"
      get "autocomplete"
    end
  end

  resources :tags, only: [ :show ]
  get "badges" => "badges#index", as: :badges

  get "rankings" => "rankings#index", as: :rankings
  get "following" => "following#index", as: :following
  resources :users do
    resource :profile
  end
  get "followers" => "followers#index", as: :followers
  resource :otherspage, only: [ :show ]
  resources :questions, only: [ :show ] do
    member do
      post "create_result"
      get "result"
    end
  end

  # ogp確認用
  get "images/ogp.png", to: "images#ogp", as: "images_ogp"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


  # Defines the root path route ("/")
  root "quiz_posts#index"
end

app/views/shared/_footer.html.erb
<div class="bg-secondary w-full">
  <div class="md:ml-5 flex flex-col md:flex-row md:justify-between md:items-center p-4">
    <div class="flex flex-col md:flex-row md:space-x-4 space-y-4 md:space-y-0">
      <%= link_to 'お問い合わせ', new_contacts_path, class: 'text-sm md:text-base text-primary text-nowrap md:font-bold' %>
      <%= link_to '利用規約', terms_of_services_path, class: 'text-sm md:text-base text-primary text-nowrap md:font-bold' %>
      <%= link_to 'プライバシーポリシー', privacy_policies_path, class: 'text-sm md:text-base text-primary text-nowrap md:font-bold' %>
    </div>
    <div class="flex items-center justify-between md:space-x-2 md:mr-5 mt-6 md:mt-0">
      <p class="text-xs md:text-sm text-primary md:font-bold">© 2024 Programming Question. All rights reserved.</p>
      <%= image_tag 'duck_face.png', class: 'w-7 h-7 md:w-10 md:h-10' %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="bg-secondary fixed top-0 w-full z-50">
  <div class="md:ml-5 mx-auto flex justify-between items-center p-4">
    <div class="flex items-center space-x-2 md:space-x-4">
      <%= image_tag 'logo.png', class: 'w-8 h-8 md:w-10 md:h-10' %>
        <%= link_to 'Programming Question', '/', class: 'text-primary font-bold text-xs md:text-lg font-frankfurter mr-10 text-nowrap' %>
          <%= search_form_for @q, url: search_quiz_posts_path, class: "flex items-center", data: { controller: "autocomplete" } do |f| %>
            <label for="q_title_or_user_name_or_questions_explanation_cont" class="sr-only">Search</label>
            <div class="flex items-center gap-4">
              <div class="relative w-full">
                <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                  <span class="material-icons text-primary">
                    search
                  </span>
                </div>
                <%= f.search_field :title_or_user_name_or_questions_explanation_cont,
                    id: "q_title_or_user_name_or_questions_explanation_cont",
                    class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary focus:border-primary block w-full ps-10 p-2.5",
                    placeholder: "検索内容を入力してください",
                    autocomplete: "off",
                    data: { 
                      autocomplete_target: "input",
                      action: "input->autocomplete#search"
                    } %>
                <ul data-autocomplete-target="results" 
                    class="absolute z-50 w-full bg-white border border-gray-300 rounded-lg mt-1 max-h-60 overflow-y-auto shadow-lg">
                </ul>
              </div>
              <%= f.submit "検索", class: "btn btn-primary btn-sm hover:opacity-70" %>
            </div>
          <% end %>
    </div>
    
    <% if user_signed_in? %>
      <div class="hidden md:flex items-center space-x-4 md:mr-5">
        <%= link_to user_profile_path(current_user.id) do %>
          <div class="text-center">
            <% if current_user.profile.present? && current_user.profile.user_icon.attached? %>
              <%= image_tag current_user.profile.user_icon, class: 'w-10 h-10 rounded-full object-cover border border-primary border-300 ml-1' %>
            <% else %>
              <%= image_tag 'profile_sample.png', class: 'w-10 h-10 rounded-full object-cover border border-primary border-300 ml-1' %>
            <% end %>
          </div>
        <% end %>
        <!--(本リリース)ブックマーク機能
        <%= link_to bookmarks_quiz_posts_path do %>
          <span class="material-icons md-36 text-primary">bookmark</span>
        <% end %>
        -->
        <%= button_to destroy_user_session_path, method: :delete, data: { turbo_method: :delete } do %>
          <span class="material-icons md-36 text-primary mt-1.5">logout</span>
        <% end %>
      </div>

      <!--(レスポンシブ)ハンバーガーメニュー -->
      <div class="flex-none md:hidden">
        <div class="dropdown dropdown-hover dropdown-end">
          <div tabindex="0" role="button" class="btn btn-ghost btn-circle btn-sm">
            <% if current_user.profile.present? && current_user.profile.user_icon.attached? %>
              <%= image_tag current_user.profile.user_icon, class: "rounded-full object-cover border border-primary border-300" %>
            <% else %>
              <%= image_tag 'profile_sample.png', class: "w-8 h-8 rounded-full object-cover border border-primary border-300" %>
            <% end %>
          </div>
          <ul tabindex="0" class="dropdown-content menu bg-white rounded-box p-2 shadow space-y-2">
            <li>
              <%= link_to 'プロフィール', user_profile_path(current_user.id), class: "text-primary text-base tracking-wide hover:opacity-70 transition duration-300 text-nowrap" %>
            </li>
            <!--(本リリース)ブックマーク機能
            <li>
              <%= link_to 'ブックマーク', bookmarks_quiz_posts_path, class: 'text-primary text-base tracking-wide hover:opacity-70 transition duration-300 text-nowrap' %>
            </li>
            -->
            <li>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: 'text-primary text-base tracking-wide hover:opacity-70 transition duration-300 text-nowrap' %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <div class="hidden md:flex space-x-8 md:mr-5">
        <%= link_to 'ログイン', new_user_session_path, class: 'text-primary font-bold text-base md:text-lg tracking-wide hover:opacity-70 transition duration-300' %>
        <%= link_to '新規登録', new_user_registration_path, class: 'text-primary font-bold text-base md:text-lg tracking-wide hover:opacity-70 transition duration-300' %>
          <!--(本リリース)パスワードリセット機能
        <%= link_to 'パスワードリセット', new_user_password_path, class: 'text-primary font-bold text-base md:text-lg tracking-wide hover:opacity-70 transition duration-300' %>
          -->
      </div>

      <!--(レスポンシブ)ハンバーガーメニュー -->
      <div class="flex-none md:hidden">
        <div class="dropdown dropdown-hover dropdown-end">
          <div tabindex="0" role="button">
            <button class="btn btn-square btn-ghost btn-sm">
              <span class="material-icons text-primary">
                menu
              </span>
            </button>
          </div>
          <ul tabindex="0" class="dropdown-content menu bg-white rounded-box p-2 shadow space-y-2">
            <li>
              <%= link_to 'ログイン', new_user_session_path, class: "text-primary text-base tracking-wide hover:opacity-70 transition duration-300 text-nowrap" %>
            </li>
            <li>
              <%= link_to '新規登録', new_user_registration_path, class: 'text-primary text-base tracking-wide hover:opacity-70 transition duration-300 text-nowrap' %>
            </li>
              <!--(本リリース)パスワードリセット機能
            <li>
              <%= link_to 'パスワードリセット', new_user_password_path, class: 'text-primary text-base tracking-wide hover:opacity-70 transition duration-300 text-nowrap' %>
            </li>
              -->
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>