config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks" }

  get "privacy_policies" => "privacy_policies#index", as: :privacy_policies
  get "terms_of_services" => "terms_of_services#index", as: :terms_of_services

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resource :contacts, only: [ :new, :create ]
  resources :quizzes
  resources :quiz_posts do
    collection do
      get :bookmarks
      post :create
      get "search"
      get "autocomplete"
    end
  end

  resources :tags, only: [ :show ]
  get "badges" => "badges#index", as: :badges

  get "rankings" => "rankings#index", as: :rankings
  get "following" => "following#index", as: :following
  resources :users do
    resource :profile
  end
  get "followers" => "followers#index", as: :followers
  resource :otherspage, only: [ :show ]
  resources :questions, only: [ :show ] do
    member do
      post "create_result"
      get "result"
    end
  end

  # ogp確認用
  get "images/ogp.png", to: "images#ogp", as: "images_ogp"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


  # Defines the root path route ("/")
  root "quiz_posts#index"
end

app/controllers/quiz_posts_controller.rb
class QuizPostsController < ApplicationController
  # 設定したprepare_meta_tagsをprivateにあってもpostコントローラー以外にも使えるようにする
  helper_method :prepare_meta_tags
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [ :index, :search, :autocomplete ]

  def index
    @quizzes = Quiz.eager_load(:user, :tags).all
    set_common_variables
  end

  def show
    @quiz = Quiz.includes(:tags, :questions).find(params[:id])
    @tags = Tag.all
    prepare_meta_tags(@quiz)
  end

  def new
    @quiz = Quiz.new
    @tags=Tag.all
    if current_user.admin?
      30.times do
        question = @quiz.questions.build
        question.choices.build # 1回だけchoicesを作成
      end
    else
      10.times do
        question = @quiz.questions.build
        question.choices.build # 1回だけchoicesを作成
      end
    end
  end

  def create
    @tags=Tag.all
    @quiz = Quiz.new(quiz_params.merge(author_user_id: current_user.id))

    @quiz.questions = @quiz.questions.select { |q| q.question.present? }

    if @quiz.save
      redirect_to quiz_post_path(@quiz), notice: "クイズを投稿しました！"
    else
      if current_user.admin?
        30.times do
          question = @quiz.questions.build
          question.choices.build # 1回だけchoicesを作成
        end
      else
        10.times do
          question = @quiz.questions.build
          question.choices.build # 1回だけchoicesを作成
        end
      end
      render :new, status: :unprocessable_entity
    end
    Rails.logger.info "Received tag_ids: #{params[:quiz][:tag_ids]}"
  end

  def edit
    @quiz = Quiz.find(params[:id])
    @tags = Tag.all
    unless @quiz.user == current_user
      redirect_to root_path, alert: "権限がありません"
    end

    # 現在の質問の数を取得
    existing_questions_count = @quiz.questions.count

    # 最大10問になるように新しいquestionを追加
    (10 - existing_questions_count).times do
      question = @quiz.questions.build
      question.choices.build # 1回だけchoicesを作成
    end
  end

  def update
    @quiz = Quiz.find_by(id: params[:id])
    @tags = Tag.all
    return redirect_to root_path, alert: "クイズが見つかりません" unless @quiz

    # 空の question を除外
    quiz_questions = quiz_params[:questions_attributes]&.values || []
    quiz_questions.reject! { |q| q[:question].blank? && q[:correct_answer].blank? && q[:choices_attributes].values.all? { |c| c.values.all?(&:blank?) } }

    # 更新するパラメータを再構築
    update_params = quiz_params.merge(questions_attributes: quiz_questions)

    if @quiz.update(update_params)
      redirect_to quiz_post_path(@quiz), notice: "クイズを更新しました！"
    else
      # バリデーションエラー時に新しい質問を追加
      existing_questions_count = @quiz.questions.count
      (10 - existing_questions_count).times do
        question = @quiz.questions.build
        question.choices.build # 1回だけchoicesを作成
      end

      render :edit, status: :unprocessable_entity
    end
  end

  def search
    @quizzes = @q.result(distinct: true).eager_load(:user, :tags)
    set_common_variables
    render :index
  end

  def autocomplete
    query = params[:q]
    require "moji"

    # 入力をひらがなに変換
    hiragana_query = query.tr("ァ-ン", "ぁ-ん")

    @quizzes = Quiz.eager_load(:user)
                   .where("quizzes.title ILIKE ? OR users.name ILIKE ? OR quizzes.name_hiragana ILIKE ?",
                         "%#{query}%", "%#{query}%", "%#{hiragana_query}%")
                   .limit(10)

    render json: QuizSerializer.new(@quizzes)
  end

  private

  def set_common_variables
    @tags = Tag.all
    @newest_quizzes = Quiz.includes(:tags).order(created_at: :desc).first(6)
    @current_user = current_user
  end

  # show画面の内容がシェアできれば良いので、設定をコントローラーで行う。
  def prepare_meta_tags(quiz)
    # このimage_urlにMiniMagicで設定したOGPの生成した合成画像を代入する
    # image_url = "#{request.base_url}/images/ogp.png?text=#{CGI.escape(quiz.title)}&questions_count=#{quiz.questions_count}&tags=#{CGI.escape(quiz.tags.pluck(:name).join(','))}"
    set_meta_tags og: {
      site_name: "Programming Question",
      title: quiz.title,
      description: "Programming Questionはプログラミングのクイズを投稿・共有できるサイトです。",
      type: "website",
      url: url_for(controller: "quiz_posts", action: "show", id: quiz.id, only_path: false),
      # image: image_url,
      locale: "ja-JP"
    },
    twitter: {
      card: "summary_large_image",
      site: "@study_kogoro"
      # image: image_url
    }
  end

  def quiz_params
    params.require(:quiz).permit(
      :title,
      tag_ids: [],
      questions_attributes: [
        :id,
        :question,
        :correct_answer,
        :answer_source,
        :explanation,
        :_destroy,
        :question_image,
        :explanation_image,
        choices_attributes: [
          :id,
          :choice1,
          :choice2,
          :choice3,
          :choice4,
          :_destroy
        ]
      ]
    )
  end
end

app/views/quiz_posts/_quiz_card.html.erb
<div class="bg-secondary grid-item rounded p-6 flex-1 my-1">
  <p class="text-accent md:text-lg">
    <%= link_to quiz.title, quiz_post_path(quiz.id) %>
  </p>
 <!-- 作成者情報 -->
  <div class="flex gap-1 items-center text-sm md:text-md">
    <%= link_to user_profile_path(quiz.user.id), class: "flex items-center gap-2" do %>
      <% if quiz.user&.profile&.user_icon&.attached? %>
        <%= image_tag quiz.user.profile.user_icon, class: 'w-6 h-6 rounded-full object-cover border border-primary border--300' %>
      <% else %>
        <%= image_tag 'profile_sample.png', class: 'w-6 h-6 rounded-full object-cover border border-primary border--300' %>
      <% end %>
    <% end %>
    <%= link_to user_profile_path(quiz.user.id), class: "flex items-center gap-2 text-sm md:text-md" do %>
      <p><%= quiz.user&.name || "作者不明" %></p>
    <% end %>
  </div>
  <!-- タグと日付 -->
  <div class="mt-2 flex items-center">
    <%= render partial: "tags/buttons/tags", locals: { tags: quiz.tags } %>
    <p class="ml-2 text-sm md:text-md"><%= quiz.created_at.strftime('%Y/%m/%d') %></p>
  </div>
</div>

app/views/quiz_posts/index.html.erb
<div class="bg-white min-h-screen overflow-auto">
  <div class="flex flex-col justify-center items-center mt-8 mb-8 mx-4 md:mx-24 lg:mx-72">
    <h1 class="text-3xl md:text-3xl lg:text-4xl font-bold text-accent text-center">
      <% content_for(:title, 'ようこそ') %>
    </h1>
  </div>

  <h1 class="text-primary text-center sm:text-xl md:text-2xl bg-secondary p-6 mt-6">プログラミングで人生の可能性を広げよう！</h1>

  <div class="flex flex-col md:flex-row gap-6 p-6 mt-6">
    <!-- Left Column -->
    <div class="w-full md:w-2/3 order-2 md:order-1">
      <div class="bg-secondary p-6 rounded shadow">
        <h2 class="text-primary font-bold sm:text-lg md:text-xl mb-4 flex items-center">
          <span class="material-icons leading-none mr-2">lightbulb_outline</span>
          <% if params[:q].present? %>
            検索結果: <%= @quizzes.count %>件
            <% if params[:q][:title_or_user_name_or_questions_explanation_cont].present? %>
              (<%= params[:q][:title_or_user_name_or_questions_explanation_cont] %>で検索)
            <% end %>
          <% else %>
            クイズを解く
          <% end %>
        </h2>

        <% if params[:q].present? && @quizzes.empty? %>
          <div class="bg-base-100 rounded p-4 text-center">
            <p class="text-gray-600">検索結果が見つかりませんでした。</p>
            <p class="text-gray-600 mt-2">別のキーワードで試してみてください。</p>
          </div>
        <% end %>

        <% if params[:q].present? %>
          <div class="bg-base-100 rounded py-2">
            <div class="grid grid-cols-1 lg:grid-cols-2 m-4 gap-4">
              <% @quizzes.each do |quiz| %>
                <%= render partial: "quiz_posts/quiz_card", locals: {quiz: quiz} %>
              <% end %>
            </div>
          </div>
        <% end %>

        <% if !params[:q].present? %>
          <h3 class="text-accent md:text-lg mb-4">クイズカテゴリ一覧</h3>
          <div class="bg-base-100 rounded p-4">
            <div class="grid grid-cols-2 lg:grid-cols-3 gap-2">
              <% @tags.each do |tag| %>
                <%= link_to tag_path(tag.id), class: "btn flex-1 md:text-lg text-white font-bold text-center text-nowrap my-1 #{tag.data_color}" do %>
                  <%= tag.name %>
                <% end %>
              <% end %>
            </div>
          </div>

          <div class="text-accent md:text-lg mt-4 mb-4">新着クイズ</div>
          <div class="bg-base-100 rounded py-2">
            <div class="grid grid-cols-1 lg:grid-cols-2 m-4 gap-4">
              <% @newest_quizzes.each do |quiz| %>
                <%= render partial: "quiz_posts/quiz_card", locals: {quiz: quiz} %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="w-full md:w-1/3 order-1 md:order-2">
      <%= link_to new_quiz_post_path, class: "block bg-secondary p-4 rounded shadow" do %>
        <h2 class="text-primary sm:text-lg md:text-xl text-center font-bold p-4 flex items-center justify-center">
        <span class="material-icons mr-2">
          add_circle_outline
        </span>
          クイズを作る
        </h2>
      <% end %>

   <!-- （本リリース）ランキング機能
<div class="bg-secondary p-6 rounded shadow mt-12">
  <h2 class="text-primary text-xl font-bold mb-2 flex items-center">
    <span class="material-icons">
      emoji_events
    </span>
    ランキング
  </h2>
  <div>
    <h4 class="text-primary mt-4 mb-2 flex items-center">
      <span class="material-icons md-36 bg-gradient-to-r from-yellow-300 via-yellow-500 to-yellow-600 text-gradient">
        military_tech
      </span>
      たくさん解かれたクイズ
    </h4>
  </div>
  <div class="bg-base-100 rounded p-6">
    <p class="text-accent text-lg">クイズタイトル</p>
    <div class="flex gap-1 items-center">
      <%= image_tag 'profile_sample.png', class: 'w-6 h-6 rounded-full object-cover border border-primary border--300' %>
      <p>作者のユーザーネーム</p>
    </div>
    <a href="/tags/1" class="btn btn-sm bg-html flex-1 text-sm text-white text-bold text-center text-nowrap mt-2">HTML</a>
    <a href="/tags/2" class="btn btn-sm bg-css flex-1 text-sm text-white text-bold text-center text-nowrap mt-2">CSS</a>
  </div>

  <h4 class="text-primary mt-4 mb-2 flex items-center">
    <span class="material-icons md-36 bg-gradient-to-r from-yellow-300 via-yellow-500 to-yellow-600 text-gradient">
      military_tech
    </span>
    クイズを解いた数が多いユーザー
  </h4>
  <div class="bg-base-100 rounded p-6">
    <div class="flex gap-1 items-center">
      <%= image_tag 'profile_sample.png', class: 'w-6 h-6 rounded-full object-cover border border-primary border--300' %>
      <p class="text-accent text-lg">ユーザーネーム</p>
    </div>
  </div>

  <h4 class="text-primary mt-4 mb-2 flex items-center">
    <span class="material-icons md-36 bg-gradient-to-r from-yellow-300 via-yellow-500 to-yellow-600 text-gradient">
      military_tech
    </span>
    レビューが高評価のクイズ
  </h4>
  <div class="bg-base-100 rounded p-6">
    <p class="text-accent text-lg">クイズタイトル</p>
    <div class="flex gap-1 items-center">
      <%= image_tag 'profile_sample.png', class: 'w-6 h-6 rounded-full object-cover border border-primary border--300' %>
      <p class="text-sm">作者のユーザーネーム</p>
    </div>
    <a href="/tags/5" class="btn btn-sm bg-git flex-1 text-sm text-white text-bold text-center text-nowrap mt-2">Git</a>
    <a href="/tags/6" class="btn btn-sm bg-error flex-1 text-sm text-white text-bold text-center text-nowrap mt-2">エラー</a>
  </div>
</div>
-->
      <div class="mt-4 flex justify-center hidden md:block">
        <%= image_tag "duck_body.png", class: 'mt-4 w-72 h-72 md:w-full h-auto' %>
      </div>
    </div>

    <div class="mt-4 flex justify-center block order-3 md:hidden">
      <%= image_tag "duck_body.png", class: 'mt-4 w-72 h-72 md:w-full h-auto' %>
    </div>
  </div>
</div>

app/views/quiz_posts/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="bg-white min-h-screen overflow-auto">
  <div class="flex flex-col justify-center items-center mt-12 mb-6 md:mb-8 mx-4 md:mx-44">
    <h1 class="text-xl md:text-3xl md:text-3xl lg:text-4xl font-bold text-accent text-center">
      <%= t('.title') %>
    </h1>
    <div class="flex flex-col w-full justify-end items-center pr-10 md:pr-20 mt-6 md:mt-0">
      <p class="text-xs md:text-sm text-primary ml-auto text-right"><%= t('.create_limit') %></p>
      <p class="text-xs md:text-sm text-primary ml-auto text-right"><%= t('.create_necessary') %></p>
    </div>
  </div>

<%= form_with model: @quiz, url: quiz_posts_path, local: true do |form| %>
  <% if @quiz.errors.any? %>
    <div class="error-messages bg-red-100 text-red-700 border border-red-400 p-4 rounded mb-4">
      <h2 class="text-lg font-bold mb-2"><%= t('.errors_blank') %></h2>
      <ul class="list-disc pl-5">
        <% @quiz.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="bg-white">
    <div class="flex bg-secondary rounded justify-center px-3 md:px-12 mx-6 md:mx-44 mb-12">
      <div class="flex flex-col w-full mt-6 mb-10 md:mb-6 mx-4 md:mx-6">
        <div class="space-y-4">
          <div class="flex flex-col bg-white rounded p-6">
            <div class="flex items-start">
              <%= form.label :title, t('.quizes_title'), class: "block mb-2 text-base md:text-lg text-nowrap font-medium text-primary" %>
              <span class="text-accent ml-1">*</span>
            </div>
            <%= form.text_field :title, class: "bg-white border border-gray-300 text-sm w-full rounded-lg forcus:ring-primary focus:border-primary block p-2.5" %>
          </div>
          <div class="bg-white rounded p-6 mb-6">
            <div class="flex items-start">
              <label for="tag" class="block mb-1 text-base md:text-lg font-medium text-primary"><%= t('.quizes_tags') %></label>
              <span class="text-accent ml-1">*</span>
            </div>
            <div class="text-xs md:text-sm text-gray-500 mb-2">
              <%= t('.tags_annotation') %>
            </div>
            <div class="bg-base-100 rounded">
              <div class="grid grid-cols-2 md:grid-cols-6 gap-2">
                <% @tags.each do |tag| %>
                  <label
                    class="tag-label btn flex-1 text-sm md:text-lg text-white text-bold text-center text-nowrap cursor-pointer <%= tag.data_color %>"
                    data-color="<%= tag.data_color %>">
                    <input
                      type="checkbox"
                      name="quiz[tag_ids][]"
                      value="<%= tag.id %>"
                      class="tag-checkbox hidden"
                      <%= 'checked' if @quiz.tag_ids.include?(tag.id) %> >
                    <%= tag.name %>
                  </label>
                <% end %>
              </div>
            </div>
          </div>
          <div class="divider"></div>
          <%= form.fields_for :questions, @current_question do |q_form| %>
            <div class="collapse collapse-arrow bg-white">
              <input type="checkbox" />
              <div class="collapse-title text-base md:text-lg font-medium text-primary"><%= t(".accordion_title", index: q_form.index + 1) %></div>
              <div class="collapse-content">
                <div class="flex flex-col bg-white rounded p-2 md:p-6">
                  <div class="flex items-start">
                    <%= q_form.label :question, t('.question'), class: "block mb-2 text-base md:text-lg text-nowrap font-medium text-primary" %>
                    <span class="text-accent ml-1">*</span>
                  </div>
                  <%= q_form.rich_text_area :question, class: "bg-white border border-gray-300 text-sm w-full rounded-lg forcus:ring-primary focus:border-primary block p-2.5 h-20" %>
                </div>
                <div class="bg-white rounded">
                  <div class="flex flex-col md:flex-row justify-between md:space-x-4 p-2 md:p-6 w-full">
                    <%= q_form.fields_for :choices do |c_form| %>
                      <div class="md:w-1/2">
                        <div class="flex items-start">
                          <%= c_form.label :choice1, t('.choices.1'), class: "block mb-2 text-base md:text-lg font-medium text-primary" %>
                          <span class="text-accent ml-1">*</span>
                        </div>
                        <%= c_form.text_area :choice1, class: "bg-white border border-gray-300 text-sm w-full rounded-lg focus:ring-primary focus:border-primary p-2.5" %>
                      </div>
                      <div class="md:w-1/2">
                        <div class="flex items-start">
                          <%= c_form.label :choice2, t('.choices.2'), class: "block mb-2 text-base md:text-lg font-medium text-primary" %>
                          <span class="text-accent ml-1">*</span>
                        </div>
                        <%= c_form.text_area :choice2, class: "bg-white border border-gray-300 text-sm w-full rounded-lg focus:ring-primary focus:border-primary p-2.5" %>
                      </div>
                      <div class="md:w-1/2">
                        <div class="flex items-start">
                          <%= c_form.label :choice3, t('.choices.3'), class: "block mb-2 text-base md:text-lg font-medium text-primary" %>
                          <span class="text-accent ml-1">*</span>
                        </div>
                        <%= c_form.text_area :choice3, class: "bg-white border border-gray-300 text-sm w-full rounded-lg focus:ring-primary focus:border-primary p-2.5" %>
                      </div>
                      <div class="md:w-1/2">
                        <div class="flex items-start">
                          <%= c_form.label :choice4, t('.choices.4'), class: "block mb-2 text-base md:text-lg font-medium text-primary" %>
                          <span class="text-accent ml-1">*</span>
                        </div>
                        <%= c_form.text_area :choice4, class: "bg-white border border-gray-300 text-sm w-full rounded-lg focus:ring-primary focus:border-primary p-2.5" %>
                      </div>
                    <% end %>
                  </div>
                </div>
                <div class="bg-white rounded p-2 md:p-6">
                  <div class="flex flex-col justify-start">
                    <div class="flex items-start">
                      <h2 class="block mb-2 text-base md:text-lg text-nowrap font-medium text-primary"><%= t('.answer') %></h2>
                      <span class="text-accent ml-1">*</span>
                    </div>
                    <%= q_form.select :correct_answer,
                      [[t('.choices.1'), 1], [t('.choices.2'), 2], [t('.choices.3'), 3], [t('.choices.4'), 4]],
                      { prompt: t('.choice_corrected_answer') },
                      { class: "select select-bordered md:w-1/2" } %>
                  </div>
                </div>
                <div class="flex flex-col bg-white rounded p-2 md:p-6">
                  <%= q_form.label :explanation, t('.explanation'), class: "block mb-2 text-base md:text-lg text-nowrap font-medium text-primary" %>
                  <%= q_form.text_area :explanation, class: "bg-white border border-gray-300 text-sm w-full rounded-lg forcus:ring-primary focus:border-primary block p-2.5 h-20" %>
                </div>
                <div class="flex flex-col bg-white rounded p-2 md:p-6">
                  <%= q_form.label :answer_source, t('.answer_source'), class: "block mb-2 text-base md:text-lg text-nowrap font-medium text-primary" %>
                  <%= q_form.text_field :answer_source, class: "bg-white border border-gray-300 text-sm w-full rounded-lg forcus:ring-primary focus:border-primary block p-2.5" %>
                </div>
                <div class="flex flex-col md:flex-row justify-start items-start md:items-center bg-white rounded p-2 md:p-6 gap-2 md:gap-8">
                  <%= q_form.label :question_image, t('.questions_image'), class: "block text-base md:text-lg text-nowrap font-medium text-primary" %>
                  <%= q_form.file_field :question_image, class: "file-input file-input-bordered file-input-primary file-input-xs md:file-input-sm w-full" %>
                </div>
                <div class="flex flex-col md:flex-row justify-start items-start md:items-center bg-white rounded p-2 md:p-6 gap-2 md:gap-8 mb-8">
                  <%= q_form.label :question_image, t('.explanation_image'), class: "block text-base md:text-lg text-nowrap font-medium text-primary" %>
                  <%= q_form.file_field :explanation_image, class: "file-input file-input-bordered file-input-primary file-input-xs md:file-input-sm w-full" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <!-- フォーム送信ボタン -->
        <div class="flex justify-center mt-6">
          <%= form.submit t('.submit'), class: "text-white bg-accent hover:opacity-70 font-medium rounded-lg text-lg w-full sm:w-auto px-5 py-2.5 text-center" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/quiz_posts/show.html.erb
<div class="bg-white min-h-screen overflow-auto">
  <div class="flex flex-col justify-center items-center mt-8 mb-8 mx-4 md:mx-24 lg:mx-72">
    <h1 class="text-3xl md:text-3xl lg:text-4xl font-bold text-accent text-center">
      <% content_for(:title, "#{@quiz.title}") %>
    </h1>
  </div>

<div class="flex justify-center m-6 md:m-12">
  <div class="bg-secondary rounded-lg p-6 mx-auto max-w-3xl w-full">
    <div class="bg-base-100 p-4 md:p-8 rounded-lg space-y-6">
      <div class="flex justify-between items-center">
        <h1 class="text-lg md:text-3xl text-accent"><%= @quiz.title %></h1>
        <div class="flex text-primary">
          <% if @quiz.author_user_id == current_user.id || current_user.admin? %>
            <!-- クイズ編集ボタン -->
            <%= link_to edit_quiz_post_path(@quiz), class: "text-primary" do %>
              <span class="material-icons md-36">edit</span>
            <% end %>
          <% end %>
          <div class="flex text-primary space-x-4">
            <% if @quiz.author_user_id == current_user.id || current_user.admin? %>
              <%= button_to @quiz,
              method: :delete do %>
                <span class="material-icons md-36" >
                  delete
                </span>
              <% end %>
            <% end %>
          </div>
          <!--(本リリース)ブックマーク機能
          <button>
            <span class="material-icons md-36">
              bookmark_border
            </span>
          </button>
          -->
        </div>
      </div>
      <div class="flex items-center gap-2">
        <%= link_to user_profile_path(@quiz.user.id) do %>
          <%= image_tag @quiz.user.profile&.user_icon&.attached? ? @quiz.user.profile.user_icon : 'profile_sample.png', class: 'w-8 h-8 rounded-full object-cover border border-primary' %>
        <% end %>
        <div class="flex md:flex-col flex-row justify-between md:flex-grow-0 flex-grow md:mt-4 items-center md:items-start">
          <%= link_to user_profile_path(@quiz.user.id) do %>
            <p class="text-primary text-base"><%= @quiz.user.name %></p>
          <% end %>
          <div>
            <p class="text-sm"><%= @quiz.created_at.strftime("%Y-%m-%d") %></p>
          </div>
          <!--(本リリース)レビュー機能
          <div class="rating rating-md rating-half">
            <input type="radio" name="rating-10" class="rating-hidden" />
            <input type="radio" name="rating-10" class="mask mask-star mask-half-1 bg-primary" />
            <input type="radio" name="rating-10" class="mask mask-star mask-half-2 bg-primary" />
            <input
              type="radio"
              name="rating-10"
              class="mask mask-star mask-half-1 bg-primary"
              checked="checked" />
            <input type="radio" name="rating-10" class="mask mask-star mask-half-2 bg-primary" />
            <input type="radio" name="rating-10" class="mask mask-star mask-half-1 bg-primary" />
            <input type="radio" name="rating-10" class="mask mask-star mask-half-2 bg-primary" />
            <input type="radio" name="rating-10" class="mask mask-star mask-half-1 bg-primary" />
            <input type="radio" name="rating-10" class="mask mask-star mask-half-2 bg-primary" />
            <input type="radio" name="rating-10" class="mask mask-star mask-half-1 bg-primary" />
            <input type="radio" name="rating-10" class="mask mask-star mask-half-2 bg-primary" />
          </div>
          -->
        </div>
      </div>
      <div class="flex flex-col md:flex-row md:justify-between">
        <div class="flex items-center gap-4">
          <% @quiz.tags.each do |tag| %>
            <%= link_to tag_path(tag.id), class: "btn btn-sm text-sm text-white font-bold text-center text-nowrap mt-2 #{tag.data_color}" do %>
              <%= tag.name %>
            <% end %>
          <% end %>
          <span class="mt-2 text-sm">全 <%= @quiz.questions_count %> 問</span>
        </div>
        <div class="mt-8 md:mt-0">
          <!-- 設定したメタタグをリダイレクトされる前に呼び出す -->
          <% prepare_meta_tags @quiz %> 
          <% twitter_share_url = "https://twitter.com/intent/tweet?url=#{CGI.escape(quiz_post_url(@quiz))}&text=#{@quiz.title}の問題を作成しました!%0A%0A&hashtags=ProgramingQuestion" %>
          <%= link_to twitter_share_url, target: "_blank", data: { toggle: "tooltip", placement: "bottom" }, title: "Xでシェア" do %>
            <button class="bg-secondary hover:opacity-70 px-4 py-1 rounded-lg shadow">
              <i class="fa-brands fa-x-twitter"></i>に共有する
            </button> 
          <% end %>
        </div>
      </div>
    </div>
    <div class="flex justify-center items-center mt-2 mb-2">
      <%= link_to 'クイズを始める', question_path(@quiz.questions.order(:id).first), class: 'text-white bg-accent hover:opacity-70 font-medium rounded-lg text-lg w-full sm:w-auto px-5 py-2.5 text-center mt-6' %>
    </div>
  </div>
</div>